### ISSUE TITLE
Offline Wallpapers 

### ISSUE THREAD

**Issue by TroubledThinker** [zixpo/candybar-sample#39]
I know this has support for cloud wallpaper but I would like built in wallpapers I can add to.

I'm relatively new to android app development as this is my first attempt. Any help is appreciated! Thanks!

**Comment by sarsamurmu** [comment]
It would increase your app size. Adding cloud wallpaper is not that hard.

**Comment by TroubledThinker** [comment]
Well I know how to add cloud wallpaper. That's easy buy I don't know how to add built-in wallpaper. If you know how, that would be much appreciated

**Comment by moertel** [comment]
It turns out this is _almost_ possible already, I just tried it out. :) Place your wallpapers in `src/assets`, for example `image.png`, and then refer to it in your wallpaper config as follows.
```json
[
  {
    "name": "Some Wallpaper Name",
    "author": "Some Author",
    "url": "file:///android_asset/image.png",
    "thumbUrl": "file:///android_asset/image.png"
  }
]
```
It is being loaded and displayed just fine. However, the `Apply` bit fails, for both lock- and homescreen. Just wondering if that would be an easy fix in CandyBar, @sarsamurmu? (I do agree that including wallpapers in the app is usually a bad idea but being able to provide wallpapers without having to use an external server to do so might be a good alternative for the less tech-savvy icon pack designers here).

**Comment by sarsamurmu** [comment]
I guess it would be easy to fix downloading issue (not sure though). Alternatively, we can just make a new fetcher for `assets` directory using [Glide's data fetcher](https://github.com/zixpo/candybar/blob/main/library/src/main/java/candybar/lib/utils/CommonDataFetcher.java)

**Comment by sarsamurmu** [comment]
It's possible now, use `assets://` instead of `https://`
